[143401485] Add front end tests.
andela/healthchecks-boomslang pull request #11
Opened 2017-04-26 13:34 UTC by andela-amutava

#### Test add check, test pushover, test my checks and test verify email
#### After cloning the repo:

- create a virtual environment 
- cd webapps/healthchecks-boomslang
- run python manage.py test hc.front.tests 
#### Relevant pivotal tracker story
Id : 143401485
Link : https://www.pivotaltracker.com/story/show/143401485

2017-05-03 12:34 UTC, collinmutembei requested changes
@andela-amutava @valeria-chemtai Attend to the comments below and ensure that the tests are passing.

2017-05-03 12:34 UTC, collinmutembei commented on hc/front/tests/test_add_check.py
> +        assert Check.objects.count() == 1
Have a look at Django's documentation on assert statements [here](https://goo.gl/Ra6s5u)

2017-05-03 12:34 UTC, collinmutembei commented on hc/front/tests/test_add_pushbover.py
> +        assert resp.status_code == 302
👀

2017-05-03 12:34 UTC, collinmutembei commented on hc/front/tests/test_add_pushbover.py
> +        assert resp.status_code == 400
👀

2017-05-03 12:34 UTC, collinmutembei commented on hc/settings.py
> +# DATABASES = {
Why is this statement commented out? Is it still needed?

2017-05-04 12:57 UTC, valeria-chemtai commented on hc/front/tests/test_add_check.py
> +        assert Check.objects.count() == 1
@collinmutembei the issues highlighted have been rectified.
Kindly check.

2017-05-04 18:22 UTC, collinmutembei commented on hc/api/tests/test_list_checks.py
> +        import ipdb; ipdb.set_trace()
Remember to remove debug statements before pushing code.

2017-05-04 18:40 UTC, valeria-chemtai commented on hc/api/tests/test_list_checks.py
> +        import ipdb; ipdb.set_trace()
@collinmutembei we must have committed that by mistake since we were doing front end tests

2017-05-08 10:56 UTC, andela-egichuri commented on hc/api/tests/test_list_checks.py
> +        import ipdb; ipdb.set_trace()
@valeria-chemtai seems like you might still need to delete this since it's on your branch.

2017-05-08 11:08 UTC, valeria-chemtai commented on hc/api/tests/test_list_checks.py
> +        import ipdb; ipdb.set_trace()
@andela-egichuri, on it.

2017-05-08 11:09 UTC, andela-egichuri commented on hc/settings.py
> +DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql_psycopg2'
Do we need this?

2017-05-08 21:28 UTC, andela-egichuri commented
Slight merge conflict here. We'll use this to explain how to solve merge conflicts.

2017-05-09 10:10 UTC, merged