Ft api tests 143489547
andela/healthchecks-boomslang pull request #14
Opened 2017-05-02 14:00 UTC by wanjiku-carol

Ft API tests 143489547

2017-05-03 12:56 UTC, collinmutembei requested changes
@wanjiku-carol @Sharonsyra Attend to the items I have highlighted with comments and ensure the tests are passing.

2017-05-03 12:56 UTC, collinmutembei commented on hc/api/tests/.cache/v/cache/lastfailed
> +{
I am not quite sure how this file came by, but I think it ought to be kept away from the repository.


**Resource**: https://goo.gl/RBRn6p

2017-05-03 12:56 UTC, collinmutembei commented on hc/api/tests/test_admin.py
> +        self.assertTrue("pushbullet", Channel.objects.create(user=self.alice, kind="pushbullet",
PEP 8 recommends ensuring statements don't go over 79 characters.Refactor this to meet that criterion.

**Resource**: https://goo.gl/iOWVQg

2017-05-03 12:56 UTC, collinmutembei commented on hc/api/tests/test_badge.py
> +        resp = self.client.get("/badge/%s/12345678/foo.svg" % self.alice.username)
While the string formatting statement is valid, I recommend using `format`.

**Resource**: https://goo.gl/NCHBiE

2017-05-03 12:56 UTC, collinmutembei commented on hc/api/tests/test_badge.py
>          url = "/badge/%s/%s/foo.svg" % (self.alice.username, sig)
Use `format` for this one too

2017-05-03 12:56 UTC, collinmutembei commented on hc/api/tests/test_list_checks.py
> +        self.assertNotEqual(checks['Alice 1']['ping_url'],
Testing with hard coded values is not a good idea.

2017-05-03 12:56 UTC, collinmutembei commented on hc/api/views.py
> +    # import ipdb
Remember to remove debug statements before pushing code.

2017-05-04 12:32 UTC, Sharonsyra commented on hc/api/tests/.cache/v/cache/lastfailed
> +{
I have added the file to .gitignore

2017-05-04 12:33 UTC, Sharonsyra commented on hc/api/tests/test_admin.py
> +        self.assertTrue("pushbullet", Channel.objects.create(user=self.alice, kind="pushbullet",
fixed the PEP 8 error

2017-05-04 12:33 UTC, Sharonsyra commented on hc/api/tests/test_badge.py
> +        resp = self.client.get("/badge/%s/12345678/foo.svg" % self.alice.username)
we have used .format instead

2017-05-04 12:34 UTC, Sharonsyra commented on hc/api/tests/test_list_checks.py
> +        self.assertNotEqual(checks['Alice 1']['ping_url'],
Noted

2017-05-08 07:22 UTC, andela-egichuri commented on .gitignore
> +hc/api/tests/.cache/v/cache/lastfailed
I think we can target directory `.cache` so that in case another file is autogenerated in a different tests directory we won't have to ignore it too

2017-05-08 07:22 UTC, andela-egichuri commented on hc/api/tests/test_admin.py
> +        self.assertTrue("pushbullet",
For this test you should be checking if `pushbullet` is listed as a channel kind."pushbullet" is specified as the kind for the channel created on [line 19](https://github.com/andela/healthchecks-boomslang/pull/14/files#diff-2f22a4dcc02da39a417848dce63db42cR19).
Please take note how `assertTrue` works => `assertTrue(expr, msg=None)`. The function only checks whether the first argument evaluates to true. The second argument is the message that should be displayed.

2017-05-08 07:26 UTC, andela-egichuri commented on hc/api/tests/.cache/v/cache/lastfailed
> +{
@Sharonsyra after adding the file to `.gitignore` you need to run `git rm -r --cached .` to remove it, since it had already been committed.

2017-05-08 07:32 UTC, andela-egichuri commented on hc/api/tests/test_badge.py
> +        self.assertTrue("svg", resp.templates)
See comment about `assertTrue` above. We should be checking the response here.

2017-05-08 07:34 UTC, andela-egichuri commented on hc/api/tests/test_create_check.py
> +        # resp = {'status_code': 201}  # This is just a placeholder variable
This should have been deleted.

2017-05-08 07:34 UTC, andela-egichuri commented on hc/api/tests/test_create_check.py
> +        # assert count change == 1
Remove commented out code.

2017-05-08 07:36 UTC, andela-egichuri commented on hc/api/tests/test_create_check.py
> +        self.assertEqual(resp.status_code, 400)
Check the error message also

2017-05-08 07:36 UTC, andela-egichuri commented on hc/api/tests/test_create_check.py
> +        # self.assertEqual(resp["error"], "could not parse request body")
The test for the error message should also pass.

2017-05-08 07:42 UTC, Sharonsyra commented on .gitignore
> +hc/api/tests/.cache/v/cache/lastfailed
i have removed .cache thanks

2017-05-08 07:42 UTC, andela-egichuri commented on hc/api/tests/test_list_checks.py
> +        self.assertTrue(payload)
Here we should check the response.

2017-05-08 07:59 UTC, Sharonsyra commented on hc/api/tests/test_create_check.py
> +        # assert count change == 1
Done

2017-05-08 12:36 UTC, wanjiku-carol commented on hc/api/tests/test_badge.py
> +        self.assertTrue("svg", resp.templates)
Corrected to assertContains.

2017-05-08 12:45 UTC, wanjiku-carol commented on hc/api/tests/test_admin.py
> +        self.assertTrue("pushbullet",
Changed to assertEqual

2017-05-08 12:53 UTC, wanjiku-carol commented on hc/api/tests/test_list_checks.py
> +        self.assertTrue(payload)
Corrected.

2017-05-08 21:17 UTC, egichuri approved these changes

2017-05-08 21:17 UTC, merged